// Mocks generated by Mockito 5.0.7 from annotations
// in survey/test/modules/side_menu/side_menu_interactor_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:rxdart/src/subjects/behavior_subject.dart' as _i2;
import 'package:survey/models/survey_info.dart' as _i6;
import 'package:survey/modules/side_menu/side_menu_module.dart' as _i3;
import 'package:survey/repositories/auth_repository.dart' as _i7;
import 'package:survey/repositories/survey_repository.dart' as _i4;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

// ignore_for_file: prefer_const_constructors

// ignore_for_file: avoid_redundant_argument_values

class _FakeBehaviorSubject<T> extends _i1.Fake
    implements _i2.BehaviorSubject<T> {}

/// A class which mocks [SideMenuInteractorDelegate].
///
/// See the documentation for Mockito's code generation for more information.
class MockSideMenuInteractorDelegate extends _i1.Mock
    implements _i3.SideMenuInteractorDelegate {
  MockSideMenuInteractorDelegate() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.BehaviorSubject<void> get logoutDidSuccess => (super.noSuchMethod(
      Invocation.getter(#logoutDidSuccess),
      returnValue: _FakeBehaviorSubject<void>()) as _i2.BehaviorSubject<void>);
  @override
  _i2.BehaviorSubject<Exception> get logoutDidFail =>
      (super.noSuchMethod(Invocation.getter(#logoutDidFail),
              returnValue: _FakeBehaviorSubject<Exception>())
          as _i2.BehaviorSubject<Exception>);
}

/// A class which mocks [SurveyRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSurveyRepository extends _i1.Mock implements _i4.SurveyRepository {
  MockSurveyRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<bool> get isSurveysCached =>
      (super.noSuchMethod(Invocation.getter(#isSurveysCached),
          returnValue: Future<bool>.value(false)) as _i5.Future<bool>);
  @override
  _i5.Future<List<_i6.SurveyInfo>> fetchSurveysFromCached() =>
      (super.noSuchMethod(Invocation.method(#fetchSurveysFromCached, []),
              returnValue:
                  Future<List<_i6.SurveyInfo>>.value(<_i6.SurveyInfo>[]))
          as _i5.Future<List<_i6.SurveyInfo>>);
  @override
  _i5.Future<List<_i6.SurveyInfo>> fetchSurveysFromRemote() =>
      (super.noSuchMethod(Invocation.method(#fetchSurveysFromRemote, []),
              returnValue:
                  Future<List<_i6.SurveyInfo>>.value(<_i6.SurveyInfo>[]))
          as _i5.Future<List<_i6.SurveyInfo>>);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i7.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isAuthenticated => (super
          .noSuchMethod(Invocation.getter(#isAuthenticated), returnValue: false)
      as bool);
  @override
  _i5.Future<void> login({String? email, String? password}) =>
      (super.noSuchMethod(
          Invocation.method(#login, [], {#email: email, #password: password}),
          returnValue: Future<void>.value(null),
          returnValueForMissingStub: Future.value()) as _i5.Future<void>);
  @override
  _i5.Future<void> logout() =>
      (super.noSuchMethod(Invocation.method(#logout, []),
          returnValue: Future<void>.value(null),
          returnValueForMissingStub: Future.value()) as _i5.Future<void>);
  @override
  _i5.Future<void> attempt() =>
      (super.noSuchMethod(Invocation.method(#attempt, []),
          returnValue: Future<void>.value(null),
          returnValueForMissingStub: Future.value()) as _i5.Future<void>);
  @override
  _i5.Future<void> fetchUser() =>
      (super.noSuchMethod(Invocation.method(#fetchUser, []),
          returnValue: Future<void>.value(null),
          returnValueForMissingStub: Future.value()) as _i5.Future<void>);
  @override
  _i5.Future<void> attemptAndFetchUser() =>
      (super.noSuchMethod(Invocation.method(#attemptAndFetchUser, []),
          returnValue: Future<void>.value(null),
          returnValueForMissingStub: Future.value()) as _i5.Future<void>);
  @override
  _i5.Future<void> resetPassword({String? email}) => (super.noSuchMethod(
      Invocation.method(#resetPassword, [], {#email: email}),
      returnValue: Future<void>.value(null),
      returnValueForMissingStub: Future.value()) as _i5.Future<void>);
}
