// Mocks generated by Mockito 5.0.7 from annotations
// in survey/test/modules/survey_questions/survey_questions_view_test.dart.
// Do not manually edit this file.

import 'package:adaptive_dialog/src/alert_dialog/alert_dialog_action.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:rxdart/src/subjects/behavior_subject.dart' as _i2;
import 'package:survey/models/survey_submit_answer_info.dart' as _i5;
import 'package:survey/modules/survey_questions/survey_questions_module.dart'
    as _i3;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

// ignore_for_file: prefer_const_constructors

// ignore_for_file: avoid_redundant_argument_values

class _FakeBehaviorSubject<T> extends _i1.Fake
    implements _i2.BehaviorSubject<T> {}

/// A class which mocks [SurveyQuestionsViewDelegate].
///
/// See the documentation for Mockito's code generation for more information.
class MockSurveyQuestionsViewDelegate extends _i1.Mock
    implements _i3.SurveyQuestionsViewDelegate {
  MockSurveyQuestionsViewDelegate() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.BehaviorSubject<void> get stateDidInit => (super.noSuchMethod(
      Invocation.getter(#stateDidInit),
      returnValue: _FakeBehaviorSubject<void>()) as _i2.BehaviorSubject<void>);
  @override
  _i2.BehaviorSubject<void> get closeButtonDidTap => (super.noSuchMethod(
      Invocation.getter(#closeButtonDidTap),
      returnValue: _FakeBehaviorSubject<void>()) as _i2.BehaviorSubject<void>);
  @override
  _i2.BehaviorSubject<_i4.OkCancelResult> get closeConfirmDialogDidClose =>
      (super.noSuchMethod(Invocation.getter(#closeConfirmDialogDidClose),
              returnValue: _FakeBehaviorSubject<_i4.OkCancelResult>())
          as _i2.BehaviorSubject<_i4.OkCancelResult>);
  @override
  _i2.BehaviorSubject<List<_i5.SurveySubmitAnswerInfo>>
      get submitButtonDidTap =>
          (super.noSuchMethod(Invocation.getter(#submitButtonDidTap),
                  returnValue:
                      _FakeBehaviorSubject<List<_i5.SurveySubmitAnswerInfo>>())
              as _i2.BehaviorSubject<List<_i5.SurveySubmitAnswerInfo>>);
  @override
  _i2.BehaviorSubject<void> get alertDialogDidClose => (super.noSuchMethod(
      Invocation.getter(#alertDialogDidClose),
      returnValue: _FakeBehaviorSubject<void>()) as _i2.BehaviorSubject<void>);
}
