// Mocks generated by Mockito 5.0.7 from annotations
// in survey/test/modules/survey_completed/survey_completed_presenter_test.dart.
// Do not manually edit this file.

import 'package:flutter/src/widgets/framework.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:survey/models/survey_question_info.dart' as _i3;
import 'package:survey/modules/survey_completed/survey_completed_module.dart'
    as _i4;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

// ignore_for_file: prefer_const_constructors

// ignore_for_file: avoid_redundant_argument_values

class _FakeBuildContext extends _i1.Fake implements _i2.BuildContext {}

class _FakeSurveyQuestionInfo extends _i1.Fake
    implements _i3.SurveyQuestionInfo {}

/// A class which mocks [SurveyCompletedView].
///
/// See the documentation for Mockito's code generation for more information.
class MockSurveyCompletedView extends _i1.Mock
    implements _i4.SurveyCompletedView {
  MockSurveyCompletedView() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set delegate(_i4.SurveyCompletedViewDelegate? _delegate) =>
      super.noSuchMethod(Invocation.setter(#delegate, _delegate),
          returnValueForMissingStub: null);
  @override
  _i2.BuildContext get context =>
      (super.noSuchMethod(Invocation.getter(#context),
          returnValue: _FakeBuildContext()) as _i2.BuildContext);
  @override
  void setOutro(_i3.SurveyQuestionInfo? outro) =>
      super.noSuchMethod(Invocation.method(#setOutro, [outro]),
          returnValueForMissingStub: null);
  @override
  void beginAnimation() =>
      super.noSuchMethod(Invocation.method(#beginAnimation, []),
          returnValueForMissingStub: null);
}

/// A class which mocks [SurveyCompletedRouter].
///
/// See the documentation for Mockito's code generation for more information.
class MockSurveyCompletedRouter extends _i1.Mock
    implements _i4.SurveyCompletedRouter {
  MockSurveyCompletedRouter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void popBack(_i2.BuildContext? context) =>
      super.noSuchMethod(Invocation.method(#popBack, [context]),
          returnValueForMissingStub: null);
}

/// A class which mocks [SurveyCompletedInteractor].
///
/// See the documentation for Mockito's code generation for more information.
class MockSurveyCompletedInteractor extends _i1.Mock
    implements _i4.SurveyCompletedInteractor {
  MockSurveyCompletedInteractor() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.SurveyQuestionInfo get outro =>
      (super.noSuchMethod(Invocation.getter(#outro),
          returnValue: _FakeSurveyQuestionInfo()) as _i3.SurveyQuestionInfo);
  @override
  set arguments(_i4.SurveyCompletedArguments? _arguments) =>
      super.noSuchMethod(Invocation.setter(#arguments, _arguments),
          returnValueForMissingStub: null);
  @override
  set delegate(_i4.SurveyCompletedInteractorDelegate? _delegate) =>
      super.noSuchMethod(Invocation.setter(#delegate, _delegate),
          returnValueForMissingStub: null);
}
