// Mocks generated by Mockito 5.0.7 from annotations
// in survey/test/modules/survey_completed/survey_completed_interactor_test.dart.
// Do not manually edit this file.

import 'package:mockito/mockito.dart' as _i1;
import 'package:survey/modules/survey_completed/survey_completed_module.dart'
    as _i2;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

// ignore_for_file: prefer_const_constructors

// ignore_for_file: avoid_redundant_argument_values

/// A class which mocks [SurveyCompletedInteractorDelegate].
///
/// See the documentation for Mockito's code generation for more information.
class MockSurveyCompletedInteractorDelegate extends _i1.Mock
    implements _i2.SurveyCompletedInteractorDelegate {
  MockSurveyCompletedInteractorDelegate() {
    _i1.throwOnMissingStub(this);
  }
}
