// Mocks generated by Mockito 5.0.7 from annotations
// in survey/test/modules/landing/landing_presenter_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:flutter/src/widgets/framework.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:streams_provider/src/streams_dispose_bag.dart' as _i4;
import 'package:survey/modules/landing/landing_module.dart' as _i3;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

// ignore_for_file: prefer_const_constructors

// ignore_for_file: avoid_redundant_argument_values

class _FakeBuildContext extends _i1.Fake implements _i2.BuildContext {}

/// A class which mocks [LandingView].
///
/// See the documentation for Mockito's code generation for more information.
class MockLandingView extends _i1.Mock implements _i3.LandingView {
  MockLandingView() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set delegate(_i3.LandingViewDelegate? _delegate) =>
      super.noSuchMethod(Invocation.setter(#delegate, _delegate),
          returnValueForMissingStub: null);
  @override
  _i2.BuildContext get context =>
      (super.noSuchMethod(Invocation.getter(#context),
          returnValue: _FakeBuildContext()) as _i2.BuildContext);
  @override
  void beginAnimation() =>
      super.noSuchMethod(Invocation.method(#beginAnimation, []),
          returnValueForMissingStub: null);
  @override
  void alert(Object? error) =>
      super.noSuchMethod(Invocation.method(#alert, [error]),
          returnValueForMissingStub: null);
}

/// A class which mocks [LandingRouter].
///
/// See the documentation for Mockito's code generation for more information.
class MockLandingRouter extends _i1.Mock implements _i3.LandingRouter {
  MockLandingRouter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void replaceToLoginScreen({_i2.BuildContext? context}) => super.noSuchMethod(
      Invocation.method(#replaceToLoginScreen, [], {#context: context}),
      returnValueForMissingStub: null);
  @override
  void replaceToHomeScreen({_i2.BuildContext? context}) => super.noSuchMethod(
      Invocation.method(#replaceToHomeScreen, [], {#context: context}),
      returnValueForMissingStub: null);
}

/// A class which mocks [LandingInteractor].
///
/// See the documentation for Mockito's code generation for more information.
class MockLandingInteractor extends _i1.Mock implements _i3.LandingInteractor {
  MockLandingInteractor() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set delegate(_i3.LandingInteractorDelegate? _delegate) =>
      super.noSuchMethod(Invocation.setter(#delegate, _delegate),
          returnValueForMissingStub: null);
  @override
  void validateAuthentication() =>
      super.noSuchMethod(Invocation.method(#validateAuthentication, []),
          returnValueForMissingStub: null);
}

/// A class which mocks [StreamsDisposeBag].
///
/// See the documentation for Mockito's code generation for more information.
class MockStreamsDisposeBag extends _i1.Mock implements _i4.StreamsDisposeBag {
  MockStreamsDisposeBag() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void add(dynamic disposable) =>
      super.noSuchMethod(Invocation.method(#add, [disposable]),
          returnValueForMissingStub: null);
  @override
  _i5.Future<void> dispose() =>
      (super.noSuchMethod(Invocation.method(#dispose, []),
          returnValue: Future<void>.value(null),
          returnValueForMissingStub: Future.value()) as _i5.Future<void>);
}
