// Mocks generated by Mockito 5.0.7 from annotations
// in survey/test/modules/landing/landing_module_test.dart.
// Do not manually edit this file.

import 'package:flutter/src/widgets/framework.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:survey/modules/landing/landing_module.dart' as _i2;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

// ignore_for_file: prefer_const_constructors

// ignore_for_file: avoid_redundant_argument_values

/// A class which mocks [LandingRouter].
///
/// See the documentation for Mockito's code generation for more information.
class MockLandingRouter extends _i1.Mock implements _i2.LandingRouter {
  MockLandingRouter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void replaceToLoginScreen({_i3.BuildContext? context}) => super.noSuchMethod(
      Invocation.method(#replaceToLoginScreen, [], {#context: context}),
      returnValueForMissingStub: null);
  @override
  void replaceToHomeScreen({_i3.BuildContext? context}) => super.noSuchMethod(
      Invocation.method(#replaceToHomeScreen, [], {#context: context}),
      returnValueForMissingStub: null);
}

/// A class which mocks [LandingInteractor].
///
/// See the documentation for Mockito's code generation for more information.
class MockLandingInteractor extends _i1.Mock implements _i2.LandingInteractor {
  MockLandingInteractor() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set delegate(_i2.LandingInteractorDelegate? _delegate) =>
      super.noSuchMethod(Invocation.setter(#delegate, _delegate),
          returnValueForMissingStub: null);
  @override
  void validateAuthentication() =>
      super.noSuchMethod(Invocation.method(#validateAuthentication, []),
          returnValueForMissingStub: null);
  @override
  void logout() => super.noSuchMethod(Invocation.method(#logout, []),
      returnValueForMissingStub: null);
}
